site_name: SS220 Developer Documentation
repo_url: https://github.com/SerbiaStrong-220/space-station-14
repo_name: SerbiaStrong-220/space-station-14
copyright: Copyright &copy; 2023 SS220. Written and maintained by TheArturZh.

theme:
    name: material
    language: ru
    palette:
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode

    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - navigation.sections

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-authors

extra:
  social:
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/ss220

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

nav:
  - Главная: index.md
  - Сборка и запуск локального сервера: localhost.md
  - Диздоки:
    - Исследователи с Сиерры(Infinity):
      - disdocs/sierra/index.md
      - disdocs/sierra/backstory-gen.md
      - disdocs/sierra/planet-gen.md
  - Маппинг:
    - mapping/mapping.md
  - Разработка:
    - development/dev-introduction.md
    - development/ecs.md
    - development/prototypes.md
    - development/basic-networking.md
    - development/creating-simple-system.md